#!/bin/sh
#
# Put this file to $PROJECT/.git/hooks/ for email notifications.
#
# You should have mail command provided by mailutils package on Debian
# based systems.
#
# sudo apt-get install mailutils
#
# You should have mail server running
#
# Do not forget: chmod +x build-failed
#
echo "
Visit http://ci.example.com/ for details.

Author:  $AUTHOR
Message:
$MESSAGE

$OUTPUT
" | mail -s "[App Name] ***FAILED*** $BRANCH build at $SHA" --to email@one.com email@two.com